const plans=[
 {amount:499,old:3999,validity:'365 Days',data:'3GB/day',voice:'Unlimited',sms:'100/day',qr:'assets/qr/qr_499.png'},
 {amount:449,old:3599,validity:'365 Days',data:'2.5GB/day',voice:'Unlimited',sms:'100/day',qr:'assets/qr/qr_449.png'},
 {amount:399,old:2599,validity:'200 Days',data:'2.5GB/day',voice:'Unlimited',sms:'100/day',qr:'assets/qr/qr_399.png'},
 {amount:349,old:1745,validity:'90 Days',data:'2GB/day',voice:'Unlimited',sms:'100/day',qr:'assets/qr/qr_349.png'},
 {amount:299,old:1245,validity:'84 Days',data:'2GB/day',voice:'Unlimited',sms:'100/day',qr:'assets/qr/qr_299.png'},
 {amount:199,old:995,validity:'56 Days',data:'1.5GB/day',voice:'Unlimited',sms:'100/day',qr:'assets/qr/qr_199.png'},
 {amount:999,old:9999,validity:'2.5 Years',data:'3GB/day',voice:'Unlimited',sms:'150/day',qr:'assets/qr/qr_999.png'}
];
const ops=[['Jio','jio'],['Airtel','airtel'],['Vi','vi'],['BSNL','bsnl']];let selected='Jio',selectedPlan=null;
const operators=document.getElementById('operators');
operators.innerHTML=ops.map(([name,cls],i)=>`<button class="operator ${i===0?'active':''}" data-op="${name}"><div class="op-logo ${cls}">${name==='BSNL'?'BSNL':name}</div><b>${name}</b>${i===0?'<span class="tick">✓</span>':''}</button>`).join('');
operators.addEventListener('click',e=>{const b=e.target.closest('.operator');if(!b)return;selected=b.dataset.op;document.querySelectorAll('.operator').forEach(x=>{x.classList.remove('active');x.querySelector('.tick')?.remove()});b.classList.add('active');b.insertAdjacentHTML('beforeend','<span class="tick">✓</span>');});
const plansEl=document.getElementById('plans');
plansEl.innerHTML=plans.map(p=>`<article class="plan"><div class="plan-top"><span class="new">✦ NEW</span><span class="plan-op">${selected} PLAN</span></div><div class="price-row"><span class="price">₹${p.amount}</span><span class="old">₹${p.old}</span><span class="data-badge">UNLIMITED<br>TRUE 5G DATA</span></div><div class="features"><div class="feature"><i>▣</i><small>VALIDITY</small><b>${p.validity}</b></div><div class="feature"><i>⌁</i><small>DATA</small><b>${p.data}</b></div><div class="feature"><i>⌕</i><small>VOICE</small><b>${p.voice}</b></div><div class="feature"><i>▤</i><small>SMS</small><b>${p.sms}</b></div></div><button class="primary choose" data-amount="${p.amount}">Recharge for ₹${p.amount} <span>→</span></button></article>`).join('');
function showPlans(){document.getElementById('plansSection').classList.remove('hidden');document.getElementById('plansHeading').textContent=`${selected} Recharge Plans`;document.querySelectorAll('.plan-op').forEach(x=>x.textContent=`${selected} PLAN`);document.getElementById('plansSection').scrollIntoView({behavior:'smooth',block:'start'});}
document.getElementById('rechargeBtn').addEventListener('click',()=>{const raw=document.getElementById('mobile').value.replace(/\D/g,'');if(raw.length!==10){alert('Please enter a valid 10-digit mobile number.');return}showPlans()});
plansEl.addEventListener('click',e=>{const btn=e.target.closest('.choose');if(!btn)return;selectedPlan=plans.find(p=>p.amount==btn.dataset.amount);openQR()});
function openQR(){document.getElementById('qrAmount').textContent=`₹${selectedPlan.amount}`;document.getElementById('qrOperator').textContent=`${selected} • Mobile recharge`;document.getElementById('qrImage').src=selectedPlan.qr;document.getElementById('proof').value='';document.getElementById('fileName').textContent='PNG, JPG or WEBP • Max 5MB';document.getElementById('uploadBtn').disabled=true;document.getElementById('qrModal').classList.add('show')}
const proof=document.getElementById('proof');proof.addEventListener('change',()=>{const f=proof.files[0];if(!f)return;if(f.size>5*1024*1024){alert('Screenshot must be 5MB or smaller.');proof.value='';return}document.getElementById('fileName').textContent=f.name;document.getElementById('uploadBtn').disabled=false});
document.getElementById('uploadBtn').addEventListener('click',()=>{if(!proof.files[0])return;document.getElementById('qrModal').classList.remove('show');const n=document.getElementById('mobile').value.replace(/\D/g,'');document.getElementById('successNumber').textContent='+91 '+n.slice(0,5)+' '+n.slice(5);document.getElementById('successAmount').textContent='₹'+selectedPlan.amount;setTimeout(()=>document.getElementById('successModal').classList.add('show'),180)});
document.querySelectorAll('[data-close]').forEach(b=>b.addEventListener('click',()=>document.getElementById(b.dataset.close).classList.remove('show')));
['qrModal','successModal'].forEach(id=>document.getElementById(id).addEventListener('click',e=>{if(e.target.id===id)e.target.classList.remove('show')}));
let seconds=14*60+27;setInterval(()=>{seconds=seconds>0?seconds-1:14*60+27;const m=String(Math.floor(seconds/60)).padStart(2,'0'),s=String(seconds%60).padStart(2,'0');document.getElementById('timer').textContent=`${m}:${s}`},1000);
